- hosts: all
  tasks: 
    - name: apt update
      become: yes
      apt:
        update_cache: yes
      
    - name: install dependencies
      become: yes
      apt:
        only_upgrade: yes
        name:
          - git-core
          - curl
          - zlib1g-dev
          - build-essential
          - libssl-dev
          - libreadline-dev
          - libyaml-dev
          - libmysqlclient-dev
          - mysql-server
          - libxml2-dev
          - libxslt1-dev
          - libcurl4-openssl-dev
          - software-properties-common
          - libffi-dev
          - dirmngr
          - gnupg
          - apt-transport-https
          - ca-certificates
          - rbenv
      

    - name: git clone rbenv ruby-build
      git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: ~/.rbenv/plugins/ruby-build

    - name: git clone rbenv-vars
      git: 
        repo: https://github.com/rbenv/rbenv-vars.git
        dest: ~/.rbenv/plugins/rbenv-vars

    - name: setup rbenv to ~/.bashrc
      shell:
        cmd: echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    
    - name: export ruby-build to PATH
      shell:
        cmd: echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc

    - name: install ruby version 3.0.1 with rbenv
      shell: 
        cmd: rbenv install -v 3.0.1

    - name: set ruby version 3.0.1 as global
      shell:
        cmd: rbenv global 3.0.1

    - name: create /app directory in root folder
      become: yes
      file:
        path: /app
        state: directory
